# Going Deeper

<p>In this session we provide a more explanation on how to use tensorflow variables and perform operations on them.  </p>

<p><b>TENSORS AND THEIR SHAPES </b></p>

<p>Shapes  characterize the <b>size</b> and <b>number of dimensions</b> of a tensor. The shape of a tensor is expressed as <i>list</i>, and  the ith element  of the list is size along dimension i. The length of the list  indicates the rank of the tensor (i.e., the number of dimensions).</p>

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt # for visualization.
import numpy as np              # Low-level numerical Python library.
import pandas as pd             # Higher-level numerical Python library.

In [5]:
with tf.Graph().as_default():
    # A scalar is a 0-D tensor.
    scalar = tf.zeros([])

    # A vector with 3 elements.
    vector = tf.zeros([3])

    # A matrix with 2 rows and 3 columns.
    matrix = tf.zeros([2, 3])

    with tf.Session() as sess:
        print 'scalar of shape', scalar.get_shape(), 'and value:\n', scalar.eval()
        print 'vector of shape', vector.get_shape(), 'and value:\n', vector.eval()
        print 'matrix of shape', matrix.get_shape(), 'and value:\n', matrix.eval()


 scalar of shape () and value:
0.0
vector of shape (3,) and value:
[ 0.  0.  0.]
matrix of shape (2, 3) and value:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


<p>The example above is similar to the first tutorial where we used tf.constant and tf.variable. The importance of having correct tensor shape  can not be over emphasized given that most of the time our errors will be mostly due to incompatible  shape .</p>

<p><b>BROADCASTING</b></p>

<p>
<p>Generally, we  perform element-wise operations (e.g. addition) on tensors of the same shape. In TensorFlow (just as in numpy), however, we mcan perform operations on tensors that would traditionally have been incompatible.</p>

<p> <b>Broadcasting</b> enables TensorFlow to automatically enlarge the smaller array in an operation to be shape compatible for  element-wise operation.</p>
When a tensor gets broadcast, its entries along that dimension get conceptually copied - for optimization purposes.</p>
</p>
For instance, broadcasting enables the following:
If an operand requires a size [7] tensor, a size [1] or a size [ ] tensor can serve as an operand.
If an operation requires a size [7, 10] tensor, any of the following sizes can serve as an operand:
   * `[1, 10]`
   * `[10]`
   * `[]`
   
If an operation requires a size `[10, 13, 19]` tensor, any of the following sizes can serve as an operand:

   * `[1, 13, 19]`
   * `[10, 1, 19]`
   * `[10, 13, 1]`
   * `[1, 1, 1]`
   * `[13, 19]`
   * `[1, 19]`
   * `[19]`
   * `[1]`
   * `[]`   

To illutrate this consider the following example. We will provide example first for 1 D and then for 1D. For more on broadcasting visit this link http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc.

In [46]:
with tf.Graph().as_default():
    # Create  vector (1-D tensor).
    matrix = tf.constant([3, 4, 4], dtype=tf.int32)
    print "this example is for Id array,: " ,matrix.shape

    # Create a constant scalar with value 1.
    value1 = tf.constant([4], dtype=tf.int32)
    


    # Add the two tensors. The resulting tensor is a six-element vector.
    evaluation1 = tf.add(value1, matrix)
    

    with tf.Session() as sess:
        print evaluation1.eval()
        

this example is for Id array,:  (3,)
[7 8 8]


In [47]:
with tf.Graph().as_default():
    # Create  matrix (2-D tensor).
    matrix = tf.constant([[3, 4, 4],[3,4,5]], dtype=tf.int32)
    print("shape of matrix is :",matrix.shape)
    print"\n"

    # Create a constant scalar with value 1.
    value1 = tf.constant([[4],[5]], dtype=tf.int32)
   
    # Evaluations
    evaluation1 = tf.add(value1, matrix)
   
    with tf.Session() as sess:
        print evaluation1.eval()
        

('shape of matrix is :', TensorShape([Dimension(2), Dimension(3)]))


[[ 7  8  8]
 [ 8  9 10]]
