# Understanding Transpose Operation In TensorFlow

Create a numpy array as below:

In [8]:
import numpy as np
import tensorflow as tf

In [3]:
array = np.array([[1, 2, 3] ,  [4, 5, 6]])

Get the shape of the array:

In [6]:
print("shape of the array is :", array.shape)

shape of the array is : (2, 3)


Lets use tf.transpose  operation on the "array" above and explain the output. This we do by parsing the array generated above into the transpose operation and run it in a session.

In [10]:
transpose_array= tf.transpose(array, perm=[1,0]) 


Run in a session

In [13]:
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print ("the transposed array is: \n " , transpose_array.eval())
    print ("the resulting shape is : " , result.shape)

the transposed array is: 
  [[1 4]
 [2 5]
 [3 6]]
the resulting shape is :  (3, 2)


Explanation: 
  We have an array of shape (2,3) and we use the tf.transpose specifying the perm=[1,0]. This optional parameter perm which we specified will basically permute the array like below:
  
      * [1,0] permute such that dimension 1 --->(becomes) 1, and dimension 0  --> 1. 
      * Basically this is exchange of dimension
      * So that array of shape  [2,3]  becomes [3,2]

# Further Complex Examples

In [15]:
twothreefour = np.array([ [[1,2,3,4], [5,6,7,8], [9,10,11,12]] , 
                        [[13,14,15,16], [17,18,19,20], [21,22,23,24]] ])

In [18]:
# shape of the array above 
print("Shape is : ", twothreefour.shape)

Shape is :  (2, 3, 4)


In [22]:
twofourthree = tf.transpose(twothreefour, perm=[0,2,1]) 
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (twofourthree.eval())
    print ("\n")
    print ("shape is: ", twofourthree.get_shape())

[[[ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]
  [ 4  8 12]]

 [[13 17 21]
  [14 18 22]
  [15 19 23]
  [16 20 24]]]


shape is:  (2, 4, 3)


Using the same explanation we have that perm [0,2,1]. Show that an array of shape (2,3,4) becaomes (2,4,3)

The last one as exercise:

In [24]:
threetwofour = tf.transpose(twothreefour, perm=[1,0,2]) 
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (threetwofour.eval())
    print("\n")
    print("My shape is:", threetwofour.get_shape())

[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


My shape is: (3, 2, 4)


Using perm= [1,0,2]. Explain the output (3,2,4) obtained from the array of shape (2,4,3) after the transpose operation in a session.

#  Placeholder

This creates a placeholder for a tensor. It is used in most mpodels to hold the dimension of variables. 

Important: This tensor will produce an error if evaluated. Its value must be fed using the <i>feed_dict</i> optional argument to Session.run( ), Tensor.eval( ), or Operation.run( ).

In [33]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
    #print(sess.run(y))  # ERROR: will fail because x was not fed.
    rand_array = np.random.rand(1024, 1024)
    
    result = sess.run(y, feed_dict={x: rand_array})  # Will succeed.
    print ("The result has shape ", result.shape)

The result has shape  (1024, 1024)


Note :
    * that in most models we feed in the training data 
    * We montly feed in the data in batches by specifying the batch_size.
    * The data is scheduled at each time and a random sample of batch size is collected and fed to model
    * This is done for computational efficiency 
    * It allows compuatation of bactch stochastic gradient.

# More Reshape and Gather Operations

Generate an array and test the gether operation. Note this approach for fast prototyping: 
    * We generate an array in Numpy and test the operations of tensor flow on it.

Use: Gather slices from params according to indices.

indices must be an integer tensor of any dimension (usually 0-D or 1-D). This is best illustrated by an example:

In [31]:
array = np.array([[1,2,3],[4,9,6],[2,3,4],[7,8,0]])

In [32]:
array.shape

(4, 3)

In [36]:
gather_output0  = tf.gather(array,[1])
gather_output01  = tf.gather(array,[2])
gather_output02  = tf.gather(array,[3])

gather_output11  = tf.gather(array,[1,2])
gather_output12  = tf.gather(array,[1,3])
gather_output13  = tf.gather(array,[3,2])




gather_output  = tf.gather(array,[1,0,2])
gather_output1  = tf.gather(array,[1,1,2])
gather_output2  = tf.gather(array,[1,2,1])



In [37]:
with tf.Session() as sess:
    print (gather_output0.eval());print("\n")
    print (gather_output01.eval());print("\n")
    print (gather_output02.eval());print("\n")  
    print (gather_output11.eval());print("\n")
    print (gather_output12.eval());print("\n")
    print (gather_output13.eval());print("\n")
    
    print (gather_output.eval());print("\n")
    print (gather_output1.eval());print("\n")
    print (gather_output2.eval());print("\n")
    #print (gather_output2.eval());print("\n")


[[4 9 6]]


[[2 3 4]]


[[7 8 0]]


[[4 9 6]
 [2 3 4]]


[[4 9 6]
 [7 8 0]]


[[7 8 0]
 [2 3 4]]


[[4 9 6]
 [1 2 3]
 [2 3 4]]


[[4 9 6]
 [4 9 6]
 [2 3 4]]


[[4 9 6]
 [2 3 4]
 [4 9 6]]


