# Import Tensorflow Operations

<b> Transpose Operations</b>

Create a numpy array as below: pay attention to the perm paramater

In [8]:
import numpy as np
import tensorflow as tf

In [3]:
array = np.array([[1, 2, 3] ,  [4, 5, 6]])

Get the shape of the array:

In [6]:
print("shape of the array is :", array.shape)

shape of the array is : (2, 3)


Lets use tf.transpose  operation on the "array" above and explain the output. This we do by parsing the array generated above into the transpose operation and run it in a session.

In [10]:
transpose_array= tf.transpose(array, perm=[1,0]) 


Run in a session

In [13]:
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print ("the transposed array is: \n " , transpose_array.eval())
    print ("the resulting shape is : " , result.shape)

the transposed array is: 
  [[1 4]
 [2 5]
 [3 6]]
the resulting shape is :  (3, 2)


Explanation: 
  We have an array of shape (2,3) and we use the tf.transpose specifying the perm=[1,0]. This optional parameter perm which we specified will basically permute the array like below:
  
      * [1,0] permute such that dimension 1 --->(becomes) 1, and dimension 0  --> 1. 
      * Basically this is exchange of dimension
      * So that array of shape  [2,3]  becomes [3,2]

# Further Examples

In [15]:
twothreefour = np.array([ [[1,2,3,4], [5,6,7,8], [9,10,11,12]] , 
                        [[13,14,15,16], [17,18,19,20], [21,22,23,24]] ])

In [18]:
# shape of the array above 
print("Shape is : ", twothreefour.shape)

Shape is :  (2, 3, 4)


In [22]:
twofourthree = tf.transpose(twothreefour, perm=[0,2,1]) 
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (twofourthree.eval())
    print ("\n")
    print ("shape is: ", twofourthree.get_shape())

[[[ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]
  [ 4  8 12]]

 [[13 17 21]
  [14 18 22]
  [15 19 23]
  [16 20 24]]]


shape is:  (2, 4, 3)


Using the same explanation we have that perm [0,2,1]. Show that an array of shape (2,3,4) becaomes (2,4,3)

The last one as exercise:

In [24]:
threetwofour = tf.transpose(twothreefour, perm=[1,0,2]) 
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (threetwofour.eval())
    print("\n")
    print("My shape is:", threetwofour.get_shape())

[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


My shape is: (3, 2, 4)


Using perm= [1,0,2]. Explain the output (3,2,4) obtained from the array of shape (2,4,3) after the transpose operation in a session.

#  Placeholder

This creates a placeholder for a tensor. It is used in most mpodels to hold the dimension of variables. 

Important: This tensor will produce an error if evaluated. Its value must be fed using the <i>feed_dict</i> optional argument to Session.run( ), Tensor.eval( ), or Operation.run( ).

In [33]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
    #print(sess.run(y))  # ERROR: will fail because x was not fed.
    rand_array = np.random.rand(1024, 1024)
    
    result = sess.run(y, feed_dict={x: rand_array})  # Will succeed.
    print ("The result has shape ", result.shape)

The result has shape  (1024, 1024)


Note :
    * that in most models we feed in the training data 
    * We montly feed in the data in batches by specifying the batch_size.
    * The data is scheduled at each time and a random sample of batch size is collected and fed to model
    * This is done for computational efficiency 
    * It allows compuatation of bactch stochastic gradient.

#  Reshape ,Gather And Dynamic_partition

Generate an array and test the gether operation. Note this approach for fast prototyping: 
    * We generate an array in Numpy and test the operations of tensor flow on it.

Use: Gather slices from params according to indices.

indices must be an integer tensor of any dimension (usually 0-D or 1-D). This is best illustrated by an example:

In [59]:
array = np.array([[1,2,3],[4,9,6],[2,3,4],[7,8,0]])

In [60]:
array.shape

(4, 3)

In [36]:
gather_output0  = tf.gather(array,[1])
gather_output01  = tf.gather(array,[2])
gather_output02  = tf.gather(array,[3])

gather_output11  = tf.gather(array,[1,2])
gather_output12  = tf.gather(array,[1,3])
gather_output13  = tf.gather(array,[3,2])




gather_output  = tf.gather(array,[1,0,2])
gather_output1  = tf.gather(array,[1,1,2])
gather_output2  = tf.gather(array,[1,2,1])



In [37]:
with tf.Session() as sess:
    print (gather_output0.eval());print("\n")
    print (gather_output01.eval());print("\n")
    print (gather_output02.eval());print("\n")  
    print (gather_output11.eval());print("\n")
    print (gather_output12.eval());print("\n")
    print (gather_output13.eval());print("\n")
    
    print (gather_output.eval());print("\n")
    print (gather_output1.eval());print("\n")
    print (gather_output2.eval());print("\n")
    #print (gather_output2.eval());print("\n")


[[4 9 6]]


[[2 3 4]]


[[7 8 0]]


[[4 9 6]
 [2 3 4]]


[[4 9 6]
 [7 8 0]]


[[7 8 0]
 [2 3 4]]


[[4 9 6]
 [1 2 3]
 [2 3 4]]


[[4 9 6]
 [4 9 6]
 [2 3 4]]


[[4 9 6]
 [2 3 4]
 [4 9 6]]




And looking at this simple example:
    * Initialise  simple array
    * test gather operation

In [44]:
array_simple = np.array([1,2,3])

In [45]:
array1.shape

(3,)

In [57]:
gather1  = tf.gather(array1,[0])
gather01 = tf.gather(array1,[1])
gather02 = tf.gather(array1,[2])

gather2 = tf.gather(array1,[1,2])
gather3 = tf.gather(array1,[0,1])

with tf.Session() as sess:
    print (gather1.eval());print("\n")
    print (gather01.eval());print("\n")
    print (gather02.eval());print("\n")
    print (gather2.eval());print("\n")
    print (gather3.eval());print("\n")

    

[1]


[2]


[3]


[2 3]


[1 2]




<b> tf.reshape( )</b>

Note:
    *  Use the same array that was initiated
    *  Do reshape using tf.reshape( )

In [64]:
array.shape # Confirm array shape

(4, 3)

In [74]:
print ("This is the array\n" ,array) # see the output and compare with the initial array,

This is the array
 [[1 2 3]
 [4 9 6]
 [2 3 4]
 [7 8 0]]


In [84]:
reshape_ops= tf.reshape(array,[-1,4]) # Note the parameters in reshpe
reshape_ops1= tf.reshape(array,[-1,3]) # Note the parameters in reshpe
reshape_ops2= tf.reshape(array,[-1,6]) # Note the parameters in reshpe

reshape_ops_back1= tf.reshape(array,[6,-1]) # Note the parameters in reshpe
reshape_ops_back2= tf.reshape(array,[3,-1]) # Note the parameters in reshpe
reshape_ops_back3= tf.reshape(array,[4,-1]) # Note the parameters in reshpe


In [86]:
with tf.Session() as sess:
    print(reshape_ops.eval());print("\n")
    print(reshape_ops1.eval());print("\n")
    print(reshape_ops2.eval());print("\n")
    print ("Output when we reverse the parameters:");print("\n")
    print(reshape_ops_back1.eval());print("\n")
    print(reshape_ops_back2.eval());print("\n")
    print(reshape_ops_back3.eval());print("\n")


[[1 2 3 4]
 [9 6 2 3]
 [4 7 8 0]]


[[1 2 3]
 [4 9 6]
 [2 3 4]
 [7 8 0]]


[[1 2 3 4 9 6]
 [2 3 4 7 8 0]]


Output when we reverse the parameters:


[[1 2]
 [3 4]
 [9 6]
 [2 3]
 [4 7]
 [8 0]]


[[1 2 3 4]
 [9 6 2 3]
 [4 7 8 0]]


[[1 2 3]
 [4 9 6]
 [2 3 4]
 [7 8 0]]




Note: The input size and output size must be the same. ---otherwise it gives error. Simple way to check this out is to 
make sure the input can be paritioned into the the reshape parameters by doing simple multiplications.

### dynamic_cell_partitions

This is declared as :
<p> <b>tf.dynamic_partition (array, partitions, num_partitions, name=None)</b> </p>

Note:
    * we decalare number_partitions --- number of partitions
    * Use our array initialised earlier
    * We declare the partition as [0 1 0 1] . This signifies the partitions we want 0's fall to one partition and 1 the other partitions given that we have two num_partitions=2.
    * The output is a list

In [96]:
print ("This is the array\n" ,array) # This is out array

This is the array
 [[1 2 3]
 [4 9 6]
 [2 3 4]
 [7 8 0]]


<p>  We show how to make two and three partitions below</p>

In [123]:
num_partitions = 2
num_partitions1 = 3

partitions = [0, 0, 1, 1]
partitions1 = [0 ,1 ,1, 2 ]

In [119]:
dynamic_ops =tf.dynamic_partition(array, partitions, num_partitions, name=None) # 2 partitions
dynamic_ops1 =tf.dynamic_partition(array, partitions1, num_partitions1, name=None) # 3 partitions


In [125]:
with tf.Session() as sess:
    run = sess.run(dynamic_ops)
    run1 = sess.run(dynamic_ops1)
    print("Output for 2 partitions: ")
    print (run[0]);print("\n")
    print(run[1]) ;print("\n")# Compare result with initial array. Out is list
    print("Output for three partitions: ")
    
    print (run1[0]);print("\n")
    print (run1[1]);print("\n")
    print (run1[2]);print("\n")


Output for 2 partitions: 
[[1 2 3]
 [4 9 6]]


[[2 3 4]
 [7 8 0]]


Output for three partitions: 
[[1 2 3]]


[[4 9 6]
 [2 3 4]]


[[7 8 0]]


